# Generated by Django 4.2.8 on 2024-03-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel_list',
            name='inner_channel_id',
        ),
        migrations.RemoveField(
            model_name='channel_list',
            name='inner_name',
        ),
    ]
