# Generated by Django 4.2.8 on 2024-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_channel_list_inner_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_list',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterUniqueTogether(
            name='channel_list',
            unique_together={('source', 'out_name')},
        ),
    ]
