# Generated by Django 4.1 on 2024-03-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_channel_list_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='catchup',
            field=models.CharField(blank=True, max_length=50, verbose_name='回看模式'),
        ),
        migrations.AddField(
            model_name='channel',
            name='catchup_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='回看天数'),
        ),
        migrations.AddField(
            model_name='channel',
            name='catchup_source',
            field=models.CharField(blank=True, max_length=50, verbose_name='回看地址'),
        ),
        migrations.AddField(
            model_name='channel',
            name='live_url',
            field=models.URLField(blank=True, null=True, verbose_name='直播地址'),
        ),
        migrations.AddField(
            model_name='channel',
            name='tvg_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='匹配用的tvg-id'),
        ),
    ]
