# Generated by Django 4.1 on 2024-03-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_channel_catchup_channel_catchup_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='logo',
            field=models.URLField(blank=True, default='', verbose_name='台标地址'),
            preserve_default=False,
        ),
    ]
