# Generated by Django 4.1 on 2024-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_channel_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='has_epg',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否有节目表'),
        ),
    ]
