# Generated by Django 4.1 on 2024-03-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_channel_has_epg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='has_epg',
        ),
    ]
