# Generated by Django 4.1 on 2024-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_channel_has_epg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='recrawl',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], db_index=True, default=0, verbose_name='是否重新获取'),
        ),
    ]
