# Generated by Django 4.1 on 2024-03-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_channel_recrawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='来源网站ID'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='descr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='sort',
            field=models.CharField(db_index=True, max_length=50, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='tvg_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='tvg-id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='tvg_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='tvg-name'),
        ),
    ]
