# Generated by Django 4.1 on 2024-03-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_channel_channel_id_alter_channel_descr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epg',
            name='chan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.channel'),
        ),
    ]
