# Generated by Django 4.1 on 2024-03-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_epg_chan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epg',
            name='chan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.channel', verbose_name='频道'),
        ),
    ]
