# Generated by Django 4.1 on 2024-03-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_epg_channel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epg',
            name='channel_id',
        ),
    ]
