# Generated by Django 4.1 on 2024-03-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_epg_channel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epg',
            old_name='chan',
            new_name='channel',
        ),
    ]
