# Generated by Django 4.2.8 on 2024-03-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_rename_chan_epg_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='source',
            field=models.CharField(blank=True, choices=[('xml', 'xml文件'), ('tvmao', '电视猫'), ('tvsou', '搜视'), ('cctv', '央视'), ('zhongshu', '中数'), ('tbc', '台湾宽频tbc'), ('mod', '中华电信MOD'), ('cabletv', '香港有线宽频caletv'), ('g4tv', '台湾四季电视'), ('icable', '香港有线宽频i-cable'), ('nowtv', '香港NOWTV'), ('tvb', '香港无线电视TVB'), ('smg', '上海广播电视'), ('btv', '北京卫视'), ('gdtv', '广东卫视'), ('hks', '香港卫视'), ('viu', 'viutv'), ('chuanliu', '川流TV'), ('mytvsuper', 'myTVSUPER'), ('gxntv', '广西网络广播电视'), ('sdtv', '山东齐鲁')], db_index=True, max_length=50, null=True, verbose_name='节目来源'),
        ),
    ]
