# Generated by Django 4.2.8 on 2024-03-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_channel_descr_alter_channel_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='descr',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='epg',
            name='descr',
            field=models.TextField(default='', verbose_name='节目描述'),
        ),
    ]
