# Generated by Django 4.2.8 on 2024-05-09 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_channel_descr_alter_epg_descr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='descr',
        ),
    ]
