# Generated by Django 4.2.8 on 2024-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_remove_channel_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='有效'),
        ),
    ]
