# Generated by Django 4.1 on 2024-03-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_channel_logo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='logo',
            field=models.URLField(blank=True, max_length=255, verbose_name='台标地址'),
        ),
    ]
