# Generated by Django 4.1 on 2024-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_channel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='logo',
            field=models.URLField(blank=True, max_length=500, verbose_name='台标地址'),
        ),
    ]
