# Generated by Django 4.1 on 2024-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_channel_live_url_alter_channel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='num',
            field=models.PositiveIntegerField(blank=True, default=9999, verbose_name='顺序号'),
        ),
    ]
